# @package env
name: procgen
env_type: Coinrun

train:
  id: procgen-${env.env_type}-v0
  done_on_life_loss: true
  size: 64
  distribution_mode: hard
  num_levels: 0
  start_level: 0
  max_episode_steps: null

test:
  id: ${env.train.id}
  done_on_life_loss: false
  size: ${env.train.size}
  distribution_mode: ${env.train.distribution_mode}
  num_levels: ${env.train.num_levels}
  start_level: ${env.train.start_level}
  max_episode_steps: null

keymap: procgen/${env.train.id}
